### ISSUE TITLE
CORS

### ISSUE THREAD

**Issue by C-Bleul** [jexxme/groupManagementAPI#13]
CORS Fehler

**Comment by jexxme** [comment]
Is dat noch nicht gefixt? Dachte ich hätte es aufm Server gelöst...

**Comment by C-Bleul** [comment]
> Is dat noch nicht gefixt? Dachte ich hätte es aufm Server gelöst...

Bro, kp. Hab nur gesehen dass seit 3 Wochen keine Änderungen gepushed wurden.

**Comment by jexxme** [comment]
Habs direkt auf dem Server gefixt mit der änderung:
![image](https://github.com/jexxme/groupManagementAPI/assets/82029475/51a14e6f-9a5a-4746-89f6-c1d49b5cdb84)
